# Generated by Django 5.0.4 on 2024-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('anio', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=20)),
            ],
        ),
    ]
