# Generated by Django 5.0.4 on 2024-04-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(max_length=1),
        ),
    ]
