# Generated by Django 5.0.4 on 2024-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_estudiante_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
